node {
     def app 
     stage('clone repository') {
      checkout scm  
    }
     stage('Initialize'){
        def dockerHome = tool 'docker'
        env.PATH = "${dockerHome}/bin:${env.PATH}"
    }
     stage('Build docker Image'){
      app = docker.build("rupeshpanwar/dockerdemo-test1")
    }
     stage('Test Image'){
       app.inside {
         sh 'echo "TEST PASSED"' 
      }  
    }
     stage('Push Image'){
       docker.withRegistry('https://registry.hub.docker.com', 'dockerhub') {            
       app.push("${env.BUILD_NUMBER}")            
       app.push("latest")   
   }
}
}
